items:
 - TeamA
 - TeamB
 - TeamC
polls:
 - name: "team-vote"
   voters:
    - TeamA 
    - TeamB 
    - TeamC 
   scores: [1, 2, 3]
 - name: 'jury-vote'
   voters:
    - juryA 
    - juryB 
   scores: [1, 2, 3]